language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: meYNOkHLJoeT4HxhQeonYJD7lHJ/plblBtLiHVo5o4rjxOFdOZKal64SOxlFd5Ds838Q5lszVP1YGeTIGXciDo60NwRU/2aIpAmhAi/91Ff0+ZcBSNamWYAcwY8mElSUgJ/WHNybZJPG7qw8GdxPXrzzYrXOs3mJoNARi85glmgLqVaZeWs/W78heKBx7OJXcdEnt7sbJk0l+L/xms1BjJivudqx12ua5HqBshXJ51FV6Ln7Mb7PQKsrPiPF6NEz6PORDnxuCfEDqZ91I5A31/9Pt7+HkqRwsBD7oBnv02R+KwD6Cz4SJ/Krxi44JjL/vlH/6t8T5kc0lLDq3IhcbYHxXiGjVNn1/+JZCOA0eGSooqC7LJ4BQmuHMUvGZhkRgYrQT3Oh/L1vr25paX//YuHKljqQneTl0ayqC3vgigurymZ97LgY+oIwe9wkz4C1KrDRY2vkSOalHi3/4LDrsjZqd7nTwbQxcR9Msk/I0R5V15ydvgF2kkKORDFOYlvD1x55ounEZ8IgXL1W3Z6/MuyRdIH5d2X8kWtR8vqtQJ2XBZB/CC8T75IF0KgvvuY8Ilw1UOkU350U50Nqvo9woWPmS/fJKqD9cWUTUdj6kyqXslU3a5+9w8Y7os8isp0BC3kZ3MCmaWXvxWPCyAwUhyU5RAZuFOnxpZa2lSjJ/9w=
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
