language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: uXbHmqsCvki7vLDRoyTzN6P4iLS4fxAkUr9KTMzTWLnCxqGhPQpHBPnIMhLVPwPWDfe51KhwH2uJnBwb2Q4jFaRf8prMoxZxQjWZmw033ZrEUS4x1qwJSU0NW5B3wmC2p91y70yeo7gC8qDJlsSdMdQoVz2VIrnkyR8/zeOgyG2lGrlcagHKJUMUzafKi0dcF9c8U/MSgC/AynPgHQwtBaJ9SBO7xsTPl8W2Lnw5GDwbPin26Ufph6wNc4UCLWUkR5Kv1HWYBGV5Q28w8BLxhCAARiu/PMC4hOjbNFVRVybyMkZXMAnJxSKqCF8qMHUQ9Ip0T475icAao+3QHzhBCbrrkwj0FOACoviB7IpJU85rfjxzG51RPrnefxKczetPT00Td4hkq2/1y8gjBk/nZ253ur8Vk7S4kZ4uh7gqfnVZ+bTw9DzFR5mnNrcfzXhQ94xE90vXRpq8VvGm5pFl0/XXg+X2LiKNMC67u0e+LZgaLfjPuqS3rdRW90PM8G6mAssS1mFPNc06q5S1ICqXcz292AqGVM5JSu4ima9NTj0Iy7KZVbfh+Ov+CvMv9po0g6JDZE/vpw0cTWbe5hSjr3v6VGFUlWOUXan9aBc2yO/D4dSLe4Uerp6JFB2AIO5rMmMUOp/y99Nj7V5+PJvGeJmmjSjdZn7I/FFm0Qpnb9E=
    on_pull_requests: false
after_success:
- mvn clean test jacoco:report coveralls:report
- mvn deploy --settings settings.xml
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: da0S1wjqL+jGyI2kdWu9nz6q6d66oKO7ElRTnYwT+ppuYkZpRz0dj6xKiQj4rBH5d8ZYGUHMMfLEU5316oHp5WSmkf7FttP/6gHcq9cbsEobbA5vdA0G+z+U+kDkzncsQXDxMbYQl3BeGs00vTkYj9u0NkHlkfRSCPJk4N19Yn7ne8T4qcTnwy41TJecPUUIU+Oe4dXt7LUtnca1vPmpU6p4KOnk93fmyLVsJWllLK+wia9zPtUiyXfMf9JIROfGhNd5a0Bzc0TF2K0EPJEhAR9f/fGIzsNKInRtql7hh8TFTFXWWNZW2+Jkoymdcs80FytWjO7FX1TC7RjYvB1CIw+ytpZxkrtXPM/B5E5IKI7vSkzBBY8gLCIEX6+5TadOXIJHJ2FvRa/9u02j8av1aMIeE+Nhlj8wcioLNM1AzNisKTUC55mo3yb1aQ3qGJxpyJBUldYK4jPrJd6OtV3vl7ZZh07nRB4CiRa5DADRFy1ylwzJEDWqEyAST6KzjO2YI28yV6sH3c+fnxv7OyZGnWtITexXpxuVXZ5Fs94F74HtbvdBB7T4Hin2eHEuV+gDpxA05HC13PVgW9ATc8NKrinkyobJRKk7YvXSC7fFaFc6GTc9RKmnXA14PdfcpslOjO9T97j4bGNksCvIqiyMDA4qukZjmjRsbs0pI2894jI=
  - secure: ar8WhWRMQsFc19xxygmdEG0qPh+8ZztYUMMFYD5RCD4X5iOfbjPdKSTb0HNk948IsoV6pmiaQUsVkqy5WuRPHX0wTNpeaZNKQ/MC/TL7JV9SQVO4f/iabEnAMLaJOfENtA0HDoTJs9eEmPGc+s64xwJTmxPBtYpFKciMcdG05Nv5/wnoc+6Xbcw/3zMbee4H+EAdOcWhE3nlX6mjVy0GaOkB7HAHmTU/+JOSDPXVDIOhNhAAJMvphV9SPMpm06SpJnvAOhz1olRvipzPqNXeoBB/8J9YNQvnMcAnyVqG0A4lyo9r+DvQeoSXV+tz/Cj0gY15UcjQpkFmtuyaYTkzTNbY15yrs6BXTI3FmQQ9M0VtI/oDzoxNJ+VRB02hxtooefAdX3zl4EBPW4p3ILZEin0ETXd9mNJ0+DbR+6/Z5Blk5TkD0PidA4MLYEErEsyY3xJpLdsto4opq1Dqk+6j+XZBCwbn17wZPz2mOqqg+YY3jhg19zuXtEg0o1Mv/17X08Kntxbl4JCykCcm3QlpoMlyHYXJg5pZbfyKPB0GtxaXiJr/u26P8MZ5QcJfbXs7Ft+s0MlKhT/AonNHbH43NCTGTXCUC4MB+WDo4j77eFIzgFknj73L/o+K3ZYV5rc9kUHstQ36kIU2pV31Dsv0MVqIdNW8FV9efn8+pe9PTYc=
